export const ICONS = {
  BACK: 'back',
  DOWNLOAD: 'download',
  EDIT: 'edit',
  EMAIL: 'email',
  LOCATION: 'location',
  SEARCH: 'search',
  TEL: 'tel',
  ATTACH: 'attach',
  MENU: 'menu',
  PHONE: 'phone',
  SMILE: 'smile',
  VIDEO: 'video',
  VOICE: 'voice',
  PLUS: 'plus',
  SEND: 'send',
  LOGO: 'logo',
} as const
